apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: syno-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs-synology # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
