apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-05-28T18:55:17Z"
  labels:
    app: kube-plex
    chart: kube-plex-0.2.3
    heritage: Tiller
    release: plex
  name: plex-kube-plex
  namespace: default
  resourceVersion: "3315242"
  selfLink: /api/v1/namespaces/default/services/plex-kube-plex
  uid: 224ad94d-817a-11e9-92dd-c03fd56f2950
spec:
  clusterIP: 10.107.81.180
  externalTrafficPolicy: Cluster
  ports:
  - name: pms
    nodePort: 31887
    port: 32400
    protocol: TCP
    targetPort: pms
  - name: http
    nodePort: 30823
    port: 80
    protocol: TCP
    targetPort: pms
  - name: https
    nodePort: 30967
    port: 443
    protocol: TCP
    targetPort: 32443
  selector:
    app: kube-plex
    release: plex
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.2.0.21
