---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-nfs-data-pv
  namespace: plex
spec:
  capacity: 
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas01.vfondevilla.com
    path: "/volume2/Datos"
