apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-kube-plex-transcode
  labels:
    app: plex
    component: transcode
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: syno-nfs-ssd
